name: Deploy GitHub Pages

on:
  push:
    branches: ["deploy"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vì thư mục public nằm ngay ngoài cùng nên chỉ cần ghi thế này:
          path: './public' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4